import React from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import {
  LayoutDashboard,
  Layout,
  Grid,
  Users,
  Code2,
  Star,
  Download,
  Settings,
  ShieldCheck,
  GitBranch,
  Play,
  Rocket,
  Activity,
  Bot,
  BarChart3,
  Terminal,
  Clock,
  Server,
  Shield,
  Wand2,
  CalendarDays,
  Sliders,
  HardDrive,
  Calendar,
  HelpCircle,
  Zap,
  FileCheck,
  BookOpen,
  Boxes,
  Database,
  FlaskConical,
  Key,
  Cpu,
  Store,
  Building2,
  CreditCard,
  Sparkles,
  Globe,
  Webhook,
  Layers,
  Link2,
  BrainCircuit,
  Radio,
} from 'lucide-react';

export const AdminSidebar: React.FC = () => {
  const router = useRouter();

  const navItems = [
    { href: '/admin', label: 'Dashboard', icon: <LayoutDashboard className="w-4 h-4" /> },
    { href: '/admin/enterprise', label: 'Enterprise Console', icon: <Globe className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/enterprise-health', label: 'Enterprise Health', icon: <Activity className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/enterprise-ai', label: 'AI Services', icon: <Cpu className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/enterprise-monitoring', label: 'Monitoring Center', icon: <BarChart3 className="w-4 h-4 text-cyan-400" /> },
    { href: '/admin/enterprise-cost', label: 'Cost Management', icon: <CreditCard className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/enterprise-support', label: 'Enterprise Support', icon: <HelpCircle className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/enterprise-releases', label: 'Release Center', icon: <Rocket className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/collaboration', label: 'Collaboration Console', icon: <Users className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/workspaces', label: 'Workspace Manager', icon: <Building2 className="w-4 h-4 text-brand-blue" /> },
    { href: '/admin/knowledge-center', label: 'Knowledge Center', icon: <BookOpen className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/document-library', label: 'Document Library', icon: <HardDrive className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/team-management', label: 'Team Management', icon: <Users className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/collaboration-analytics', label: 'Collaboration Analytics', icon: <BarChart3 className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/automation', label: 'Enterprise Automation', icon: <Zap className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/workflow-manager', label: 'Workflow Engine', icon: <GitBranch className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/business-rules', label: 'Business Rules', icon: <ShieldCheck className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/rpa-center', label: 'RPA Manager', icon: <Bot className="w-4 h-4 text-cyan-400" /> },
    { href: '/admin/integration-center', label: 'Integration Hub', icon: <Link2 className="w-4 h-4 text-blue-400" /> },
    { href: '/admin/process-analytics', label: 'Process Analytics', icon: <BarChart3 className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/modelops', label: 'ModelOps Console', icon: <Layers className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/dataset-manager', label: 'Dataset Manager', icon: <Database className="w-4 h-4 text-cyan-400" /> },
    { href: '/admin/training-center', label: 'Training Center', icon: <Cpu className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/model-registry', label: 'Model Registry', icon: <Layers className="w-4 h-4 text-indigo-400" /> },
    { href: '/admin/deployments', label: 'Deployment Manager', icon: <Zap className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/ai-performance', label: 'AI Performance', icon: <Activity className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/developer-cloud', label: 'Developer Cloud Console', icon: <Terminal className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/repositories', label: 'Repository Center', icon: <GitBranch className="w-4 h-4 text-cyan-400" /> },
    { href: '/admin/pipelines', label: 'CI/CD Pipelines', icon: <Play className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/build-runners', label: 'Build Runners', icon: <Cpu className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/container-registry', label: 'Container Registry', icon: <Boxes className="w-4 h-4 text-indigo-400" /> },
    { href: '/admin/deployment-center', label: 'Deployment Center', icon: <Rocket className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/platform', label: 'Platform Console', icon: <Boxes className="w-4 h-4 text-cyan-400" /> },
    { href: '/admin/platform-health', label: 'Platform Health', icon: <Activity className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/platform-config', label: 'Configuration Center', icon: <Sliders className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/platform-backups', label: 'Backup Center', icon: <HardDrive className="w-4 h-4 text-blue-400" /> },
    { href: '/admin/platform-maintenance', label: 'Maintenance Center', icon: <Calendar className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/platform-releases', label: 'Release Center', icon: <Rocket className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/platform-support', label: 'Enterprise Support', icon: <HelpCircle className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/security', label: 'Security Console', icon: <Shield className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/identity', label: 'Identity Management', icon: <Key className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/organizations', label: 'Organization Manager', icon: <Building2 className="w-4 h-4 text-blue-400" /> },
    { href: '/admin/security-center', label: 'Zero Trust Center', icon: <ShieldCheck className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/threat-intelligence', label: 'Threat Intelligence', icon: <Activity className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/vulnerabilities', label: 'Vulnerability Center', icon: <Boxes className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/compliance', label: 'Compliance Center', icon: <ShieldCheck className="w-4 h-4 text-cyan-400" /> },
    { href: '/admin/audit-logs', label: 'Audit Logs', icon: <BarChart3 className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/data-platform', label: 'Data Platform Console', icon: <Database className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/data-governance', label: 'Data Governance', icon: <Shield className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/pipeline-manager', label: 'Pipeline Manager', icon: <GitBranch className="w-4 h-4 text-cyan-400" /> },
    { href: '/admin/data-quality', label: 'Data Quality', icon: <Activity className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/analytics-center', label: 'Analytics Center', icon: <BarChart3 className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/data-catalog', label: 'Data Catalog', icon: <Boxes className="w-4 h-4 text-blue-400" /> },
    { href: '/admin/cloud-platform', label: 'Cloud Platform Console', icon: <Server className="w-4 h-4 text-cyan-400" /> },
    { href: '/admin/tenants', label: 'Tenant Manager', icon: <Building2 className="w-4 h-4 text-blue-400" /> },
    { href: '/admin/resource-manager', label: 'Resource Manager', icon: <Boxes className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/cloud-health', label: 'Cloud Infrastructure', icon: <Activity className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/capacity-planning', label: 'Capacity Planning', icon: <BarChart3 className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/cloud-billing', label: 'Cloud Billing', icon: <CreditCard className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/commerce', label: 'Commerce Console', icon: <CreditCard className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/payments', label: 'Payment Orchestration', icon: <CreditCard className="w-4 h-4 text-blue-400" /> },
    { href: '/admin/subscriptions', label: 'Subscription Manager', icon: <Sparkles className="w-4 h-4 text-purple-400" /> },
    { href: '/admin/licenses', label: 'License Key Center', icon: <Key className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/revenue', label: 'Revenue Analytics', icon: <BarChart3 className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/software-engineering', label: 'Software Engineering Console', icon: <Cpu className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/projects', label: 'Project Manager', icon: <Boxes className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/repositories', label: 'Repository Center', icon: <GitBranch className="w-4 h-4 text-brand-violet" /> },
    { href: '/admin/security-center', label: 'Security Center', icon: <Shield className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/testing-center', label: 'Testing Center', icon: <Play className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/engineering-analytics', label: 'Engineering Analytics', icon: <BarChart3 className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/marketplace', label: 'Marketplace Console', icon: <Store className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/publishers', label: 'Publisher Center', icon: <ShieldCheck className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/plugins', label: 'Plugin Registry', icon: <Boxes className="w-4 h-4 text-brand-violet" /> },
    { href: '/admin/extensions', label: 'Extension Manager', icon: <Globe className="w-4 h-4 text-blue-400" /> },
    { href: '/admin/marketplace-analytics', label: 'Marketplace Analytics', icon: <BarChart3 className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/licenses', label: 'License Center', icon: <Key className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/app-builder', label: 'Application Builder', icon: <Layout className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/components', label: 'Component Library', icon: <Boxes className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/templates', label: 'Template Marketplace', icon: <Store className="w-4 h-4 text-brand-violet" /> },
    { href: '/admin/builds', label: 'Build Pipeline', icon: <Terminal className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/deployments', label: 'Deployment Center', icon: <Rocket className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/ai-gateway', label: 'AI Gateway', icon: <Cpu className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/providers', label: 'Provider Manager', icon: <Boxes className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/prompts', label: 'Prompt Library', icon: <BookOpen className="w-4 h-4 text-brand-violet" /> },
    { href: '/ai-gateway/health', label: 'Model Monitor', icon: <Activity className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/token-usage', label: 'Token Analytics', icon: <BarChart3 className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/platform', label: 'Unified OS Console', icon: <Cpu className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/integrations', label: 'Integrations Console', icon: <Globe className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/api', label: 'API Gateway Admin', icon: <Cpu className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/webhooks', label: 'Webhooks Monitor', icon: <Webhook className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/oauth', label: 'OAuth Applications', icon: <Shield className="w-4 h-4 text-brand-violet" /> },
    { href: '/admin/data-platform', label: 'Data Platform Console', icon: <Database className="w-4 h-4 text-blue-400" /> },
    { href: '/admin/lts', label: 'v4.0 LTS Center', icon: <ShieldCheck className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/agent-cloud', label: 'Agent Cloud Console', icon: <Bot className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/runtime-v2', label: 'AI Runtime Console v2', icon: <Cpu className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/knowledge', label: 'Knowledge Cloud', icon: <Database className="w-4 h-4 text-brand-cyan" /> },
    { href: '/knowledge/chat', label: 'Enterprise RAG', icon: <Bot className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/vector-indexes', label: 'Vector Database', icon: <Layers className="w-4 h-4 text-violet-400" /> },
    { href: '/admin/connectors', label: 'Knowledge Connectors', icon: <Link2 className="w-4 h-4 text-blue-400" /> },
    { href: '/knowledge/memory', label: 'Conversation Memory', icon: <BrainCircuit className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/enterprise', label: 'Enterprise Console', icon: <Building2 className="w-4 h-4 text-brand-cyan" /> },
    { href: '/enterprise/employees', label: 'Digital Workforce', icon: <Bot className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/business-processes', label: 'Business Processes', icon: <Layers className="w-4 h-4 text-violet-400" /> },
    { href: '/enterprise/approvals', label: 'Approval Center', icon: <Clock className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/organization', label: 'Organization Dashboard', icon: <Activity className="w-4 h-4 text-blue-400" /> },
    { href: '/admin/super-platform', label: 'Super Platform Console', icon: <Sparkles className="w-4 h-4 text-emerald-400" /> },
    { href: '/super-platform/clusters', label: 'Global AI Network', icon: <Globe className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/governance', label: 'AI Governance', icon: <ShieldCheck className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/observability', label: 'Platform Observability', icon: <Radio className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/releases', label: 'Release Center v5.4', icon: <Sparkles className="w-4 h-4 text-violet-400" /> },
    { href: '/admin/cloud', label: 'Enterprise Cloud Console', icon: <Server className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/workflows', label: 'Workflow Operations', icon: <Layers className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/clusters', label: 'Cluster Management', icon: <Boxes className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/tenants', label: 'SaaS Tenants', icon: <Building2 className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/billing', label: 'SaaS Billing', icon: <CreditCard className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/plans', label: 'Plans Manager', icon: <Sparkles className="w-4 h-4 text-rose-400" /> },
    { href: '/admin/payments', label: 'Payment Ledger', icon: <CreditCard className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/testing', label: 'Testing Dashboard', icon: <Activity className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/submissions', label: 'Submission Queue', icon: <ShieldCheck className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/upload', label: 'Owner Upload Portal', icon: <Rocket className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/marketplace', label: 'AI Marketplace Admin', icon: <Store className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/models', label: 'AI Models Registry', icon: <Boxes className="w-4 h-4 text-brand-violet" /> },
    { href: '/ai-platform/deployments', label: 'Model Deployments', icon: <Rocket className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/runtime', label: 'AI Runtime Telemetry', icon: <Cpu className="w-4 h-4 text-brand-cyan" /> },
    { href: '/ai-platform/datasets', label: 'Datasets Library', icon: <Database className="w-4 h-4 text-amber-400" /> },
    { href: '/ai-platform/experiments', label: 'Experiments', icon: <FlaskConical className="w-4 h-4 text-rose-400" /> },
    { href: '/ai-platform/endpoints', label: 'Endpoints & API Keys', icon: <Key className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/agents', label: 'AI Agents Console', icon: <Bot className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/planner', label: 'Sprint Planner', icon: <CalendarDays className="w-4 h-4 text-amber-400" /> },
    { href: '/agents/reviews', label: 'Code Review', icon: <FileCheck className="w-4 h-4 text-rose-400" /> },
    { href: '/agents/documentation', label: 'Documentation Generator', icon: <BookOpen className="w-4 h-4 text-brand-cyan" /> },
    { href: '/builder', label: 'AI Builder Console', icon: <Wand2 className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/operations', label: 'Operations Console', icon: <Activity className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/system', label: 'System Telemetry', icon: <Server className="w-4 h-4 text-brand-violet" /> },
    { href: '/admin/audit', label: 'Audit Logs', icon: <Shield className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/logs', label: 'System Log Stream', icon: <Terminal className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/deployments', label: 'Deployments', icon: <Rocket className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/jobs', label: 'Job Scheduler', icon: <Clock className="w-4 h-4 text-amber-400" /> },
    { href: '/admin/organizations', label: 'Organizations', icon: <Building2 className="w-4 h-4 text-emerald-400" /> },
    { href: '/admin/apps', label: 'App Management', icon: <Grid className="w-4 h-4" /> },
    { href: '/admin/users', label: 'Users & Roles', icon: <Users className="w-4 h-4" /> },
    { href: '/admin/developers', label: 'Developers', icon: <Code2 className="w-4 h-4" /> },
    { href: '/admin/reviews', label: 'Reviews Moderation', icon: <Star className="w-4 h-4" /> },
    { href: '/admin/downloads', label: 'Download Logs', icon: <Download className="w-4 h-4" /> },
    { href: '/admin/analytics', label: 'Enterprise Analytics', icon: <BarChart3 className="w-4 h-4 text-brand-cyan" /> },
    { href: '/admin/automation', label: 'AI Automation', icon: <Bot className="w-4 h-4 text-brand-violet" /> },
    { href: '/admin/settings', label: 'System Settings', icon: <Settings className="w-4 h-4" /> },
  ];

  return (
    <aside className="w-full lg:w-64 shrink-0">
      <div className="glass-panel p-3 rounded-3xl border border-white/10 flex lg:flex-col overflow-x-auto lg:overflow-visible gap-1.5 scrollbar-none sticky top-20">
        <div className="hidden lg:flex items-center gap-2 px-4 py-2 border-b border-white/10 mb-1">
          <ShieldCheck className="w-4 h-4 text-brand-cyan" />
          <span className="text-[11px] font-bold uppercase tracking-wider text-text-muted">Console Menu</span>
        </div>

        {navItems.map((item) => {
          const isActive = router.pathname === item.href;

          return (
            <Link
              key={item.href}
              href={item.href}
              className={`flex items-center gap-3 px-4 py-3 rounded-2xl text-xs font-semibold whitespace-nowrap transition-all ${
                isActive
                  ? 'bg-gradient-to-r from-brand-cyan/20 to-brand-violet/20 text-white border border-brand-cyan/30 shadow-glow-cyan'
                  : 'text-text-secondary hover:text-white hover:bg-white/5 border border-transparent'
              }`}
            >
              <span className={isActive ? 'text-brand-cyan' : 'text-text-muted'}>
                {item.icon}
              </span>
              <span>{item.label}</span>
            </Link>
          );
        })}
      </div>
    </aside>
  );
};
